categoriearticle_index:
    path:     /
    defaults: { _controller: "CommercialBundle:CategorieArticle:index" }
    methods:  GET

categoriearticle_show:
    path:     /{id}/show
    defaults: { _controller: "CommercialBundle:CategorieArticle:show" }
    methods:  GET

categoriearticle_new:
    path:     /new
    defaults: { _controller: "CommercialBundle:CategorieArticle:new" }
    methods:  [GET, POST]

categoriearticle_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommercialBundle:CategorieArticle:edit" }
    methods:  [GET, POST]

categoriearticle_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommercialBundle:CategorieArticle:delete" }
    methods:  DELETE
